vervsion: 2
jobs:
    build: 
        docker:
          - image: circleci/golang:1.13

        working_directory: ~/repo
       
        steps:
            - checkout 

            - setup_remote_docker
        
            - run: 
                name: Install Docker Compose 
                command: | 
                  set -x curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > sudo /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose
             
            - run:
                name: Starts creating images and containers
                command: docker-compose up --build -d
            - run:
                name: Test 
                command: |
                  make test 

    # test:
    #     docker:
    #     steps:        
    #         - run:
    #             name: Test 
    #             command: |
    #               make test 
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                  - build
                filters:
                  branches:
                    only: experiment