vervsion: 2
jobs:
    build: 
        docker:
          - image: circleci/golang:1.13

        working_directory: /go/src/github.com/renegmed/circleci-docker-compose 
       
        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout 

            - setup_remote_docker
        
            - run: mkdir -p $TEST_RESULTS

            - run: 
                name: Install Docker Compose 
                command: | 
                  set -x curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > sudo /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose
             
            - run:
                name: Starts creating images and containers
                command: docker-compose up --build -d
            - run:
                name: Containers info
                command: docker logs originator && docker logs saleshandler  
            - run:
                name: Get GOPATH info
                command: echo $GOPATH
            - run: 
                name: Get GOROOT info
                command: echo $GOROOT
            - run:
                name: Check originator server
                command: ping -c 5 127.0.0.1
            - run:
                name: Test 
                command: |
                  make test 

    # test:
    #     docker:
    #     steps:        
    #         - run:
    #             name: Test 
    #             command: |
    #               make test 
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                  - build
                filters:
                  branches:
                    only: experiment